const languages = {
    en: {
        languageName: "English",
        title: "MATRON",
        gameMode: "Game Mode",
        twoPlayers: "2 Players",
        vsComputer: "vs Computer",
        aiDifficulty: "AI Difficulty",
        easy: "Easy",
        medium: "Medium",
        hard: "Hard",
        boardSize: "Board Size",
        player1: "Player 1",
        player2: "Player 2",
        computer: "Computer",
        score: "Score",
        lastMove: "Last Move",
        factorsUsed: "Factors Used",
        yourTurn: "Your Turn",
        waiting: "Waiting...",
        newGame: "New Game",
        instructions: "Instructions",
        howToPlay: "How to Play",
        computerThinking: "Computer is thinking...",
        selectNumber: "Select a number to start",
        gameOver: "Game over!",
        wins: "wins with",
        points: "points",
        tie: "It's a tie with",
        pointsEach: "points each",
        noFactors: "This number has no uncolored factors.",
        losesTurn: "loses their turn.",
        selected: "selected",
        received: "received all factors",
        pointsAdded: "points added",
        gameModes: "Game Modes",
        twoPlayersDesc: "Two human players take turns playing the game.",
        vsComputerDesc: "Play against the AI with three difficulty levels:",
        easyDesc: "The computer makes random valid moves.",
        mediumDesc: "The computer chooses better moves based on a points ratio.",
        hardDesc: "The computer uses advanced strategies and considers future moves."
    },
    tr: {
        languageName: "Türkçe",
        title: "MATRON",
        gameMode: "Oyun Modu",
        twoPlayers: "2 Oyuncu",
        vsComputer: "Bilgisayara Karşı",
        aiDifficulty: "Yapay Zeka Zorluğu",
        easy: "Kolay",
        medium: "Orta",
        hard: "Zor",
        boardSize: "Tahta Boyutu",
        player1: "Oyuncu 1",
        player2: "Oyuncu 2",
        computer: "Bilgisayar",
        score: "Puan",
        lastMove: "Son Hamle",
        factorsUsed: "Kullanılan Çarpanlar",
        yourTurn: "Sıra Sizde",
        waiting: "Bekleniyor...",
        newGame: "Yeni Oyun",
        instructions: "Nasıl Oynanır",
        howToPlay: "Oyun Kuralları",
        computerThinking: "Bilgisayar düşünüyor...",
        selectNumber: "Başlamak için bir sayı seçin",
        gameOver: "Oyun bitti!",
        wins: "kazandı",
        points: "puan",
        tie: "Berabere",
        pointsEach: "puan ile",
        noFactors: "Bu sayının renklendirilmemiş çarpanı yok.",
        losesTurn: "sırasını kaybetti.",
        selected: "seçti",
        received: "tüm çarpanları aldı",
        pointsAdded: "puan eklendi",
        gameModes: "Oyun Modları",
        twoPlayersDesc: "İki insan oyuncu sırayla oynar.",
        vsComputerDesc: "Üç zorluk seviyesinde yapay zekaya karşı oynayın:",
        easyDesc: "Bilgisayar rastgele geçerli hamleler yapar.",
        mediumDesc: "Bilgisayar puan oranına göre daha iyi hamleler seçer.",
        hardDesc: "Bilgisayar gelişmiş stratejiler kullanır ve gelecek hamleleri düşünür."
    },
    es: {
        languageName: "Español",
        title: "MATRON",
        gameMode: "Modo de Juego",
        twoPlayers: "2 Jugadores",
        vsComputer: "vs Computadora",
        aiDifficulty: "Dificultad de la IA",
        easy: "Fácil",
        medium: "Medio",
        hard: "Difícil",
        boardSize: "Tamaño del Tablero",
        player1: "Jugador 1",
        player2: "Jugador 2",
        computer: "Computadora",
        score: "Puntuación",
        lastMove: "Último Movimiento",
        factorsUsed: "Factores Usados",
        yourTurn: "Tu Turno",
        waiting: "Esperando...",
        newGame: "Nuevo Juego",
        instructions: "Instrucciones",
        howToPlay: "Cómo Jugar",
        computerThinking: "La computadora está pensando...",
        selectNumber: "Selecciona un número para comenzar",
        gameOver: "¡Juego terminado!",
        wins: "gana con",
        points: "puntos",
        tie: "Empate con",
        pointsEach: "puntos cada uno",
        noFactors: "Este número no tiene factores sin colorear.",
        losesTurn: "pierde su turno.",
        selected: "seleccionó",
        received: "recibió todos los factores",
        pointsAdded: "puntos añadidos",
        gameModes: "Modos de Juego",
        twoPlayersDesc: "Dos jugadores humanos se turnan para jugar.",
        vsComputerDesc: "Juega contra la IA con tres niveles de dificultad:",
        easyDesc: "La computadora hace movimientos aleatorios válidos.",
        mediumDesc: "La computadora elige mejores movimientos basados en una proporción de puntos.",
        hardDesc: "La computadora usa estrategias avanzadas y considera movimientos futuros."
    },
    ru: {
        languageName: "Русский",
        title: "МАТРОН",
        gameMode: "Режим игры",
        twoPlayers: "2 Игрока",
        vsComputer: "против Компьютера",
        aiDifficulty: "Сложность ИИ",
        easy: "Легкий",
        medium: "Средний",
        hard: "Сложный",
        boardSize: "Размер поля",
        player1: "Игрок 1",
        player2: "Игрок 2",
        computer: "Компьютер",
        score: "Счет",
        lastMove: "Последний ход",
        factorsUsed: "Использованные множители",
        yourTurn: "Ваш ход",
        waiting: "Ожидание...",
        newGame: "Новая игра",
        instructions: "Инструкции",
        howToPlay: "Как играть",
        computerThinking: "Компьютер думает...",
        selectNumber: "Выберите число для начала",
        gameOver: "Игра окончена!",
        wins: "выигрывает с",
        points: "очками",
        tie: "Ничья с",
        pointsEach: "очками у каждого",
        noFactors: "У этого числа нет неокрашенных множителей.",
        losesTurn: "теряет ход.",
        selected: "выбрал",
        received: "получил все множители",
        pointsAdded: "очков добавлено",
        gameModes: "Режимы игры",
        twoPlayersDesc: "Два игрока по очереди делают ходы.",
        vsComputerDesc: "Играйте против ИИ с тремя уровнями сложности:",
        easyDesc: "Компьютер делает случайные допустимые ходы.",
        mediumDesc: "Компьютер выбирает лучшие ходы на основе соотношения очков.",
        hardDesc: "Компьютер использует продвинутые стратегии и учитывает будущие ходы."
    }
}; 